---
# - hosts: "{{ groups['primnodes'][0]|trim }}"
 - hosts: oranodes
   name: "Display status and info about DataGuard-Config"

   become: yes
   become_user: root

   vars:
       ansible_remote_tmp: /tmp
       oracle_env:
              ORACLE_HOME:     "{{ oracle_home_19000 }}"
              LD_LIBRARY_PATH: "{{ oracle_lib_19000 }}"
              PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/lib64:/usr/lib:{{ oracle_home_19000 }}/bin:{{ oracle_lib_19000 }}
              TNS_ADMIN:  "{{ oracle_home_19000 }}/network/admin"

   strategy: debug
   tasks:

   - name: "Include variables for RedHat"
     include_vars: /home/ansible/BNP_POC_DGuard/vars/poc/poc.el7.global.yml
     tags: 01_incvars

   - name: "Include variables for RedHat and start configuring DataGuard"
     debug:
       msg: '==> HOST : {{ node }} DB : {{ dbname }}'
     failed_when:
       - node not in groups['oranodes']
     when:
       - node in groups['oranodes']
     tags: 01_chknode

   - name: Verify archivelog parameters
     become_user: "{{ oracle_user }}"
     become_method: sudo
     no_log: no
     shell: |
         export ORACLE_HOME={{ oracle_home_19000 }}; export ORACLE_SID={{ dbname }}; export PATH=$PATH:$ORACLE_HOME/bin
         {{ oracle_home_19000 }}/bin/sqlplus -s {{ sys_user }}/{{ slussel_sys }}@{{ dbname }} as sysdba <<EOF
         set feedback off;
         set heading on;
         SET SERVEROUTPUT ON SIZE 5000;
         SET LINESIZE 2500;
         set pagesize 5000;
         set long 5000;
         select NAME "db_name",DB_UNIQUE_NAME "db_unique_name",DATABASE_ROLE "db_role",LOG_MODE "log_mode",FORCE_LOGGING "force_logging" from v\$database where LOG_MODE = 'ARCHIVELOG';
     when:
       - node in groups['oranodes']
     register: sqloutput
     tags: 02_veriflog

   - name: Show result
     debug:
       msg: |
         ======================================================================
         Log Information for Database: {{ dbname }}
         ======================================================================
         ==> Database role should be PHYSICAL STANDBY for Standby DB {{ dbstby }}
         ==> Database role should be PRIMARY for Primary DB {{ dbprim }}
         {{ sqloutput.stdout }}


     when:
       - node in groups['oranodes']
     failed_when: "'no rows selected' in sqloutput.stdout"
     tags: 02_veriflog

   - name: Log Information for Database {{ dbname }}
     pause:
       prompt: 
         - Database role should be PRIMARY for Primary DB {{ dbprim }} and Database role should be PHYSICAL STANDBY for Standby DB {{ dbstby }}
     tags: 02_veriflog

   - name: Verify APPLYING_LOG on standby 
     delegate_to: "{{groups['oranodes'][1]}}"
     become_user: "{{ oracle_user }}"
     shell: |
         export ORACLE_HOME={{ oracle_home_19000 }}; export ORACLE_SID={{ dbname }}; export PATH=$PATH:$ORACLE_HOME/bin
         {{ oracle_home_19000 }}/bin/sqlplus -s {{ sys_user }}/{{ slussel_sys }}@{{ dbname }} as sysdba <<EOF
         set feedback off;
         set heading on;
         SET SERVEROUTPUT ON SIZE 5000;
         SET LINESIZE 2500;
         set pagesize 5000;
         set long 5000;
         SELECT process,
         status,
         thread#,
         sequence#,
         blocks
         FROM v\$managed_standby
         WHERE process LIKE '%MRP%';
     register: sqloutput
     when:
       - node in groups['oranodes'][1]
     tags: 03_veriftrans

   - name: Show result
     debug:
       msg: |
         Log Information for Database: {{ dbname }} ==> STATUS must be APPLYING_LOG on the standby DB {{ dbname }}
         ======================================================================================================
         {{ sqloutput.stdout }}


     when:
       - node in groups['oranodes'][1]
     failed_when: "'no rows selected' in sqloutput.stdout"
     tags: 03_veriftrans

   - name: Check for gaps between Prim and Stby
     delegate_to: "{{groups['oranodes'][1]}}"
     become_user: "{{ oracle_user }}"
     shell: |
         export ORACLE_HOME={{ oracle_home_19000 }}; export ORACLE_SID={{ dbname }}; export PATH=$PATH:$ORACLE_HOME/bin
         {{ oracle_home_19000 }}/bin/sqlplus -s {{ sys_user }}/{{ slussel_sys }}@{{ dbname }} as sysdba <<EOF
         set feedback off;
         set heading on;
         set lines 200;
         set pagesize 5000;
         set long 5000;
         col dest_name format a20;
         SELECT dest_name,
         status,
         TYPE,
         database_mode,
         recovery_mode,
         protection_mode,
         archived_seq#,
         applied_seq#,
         error,
         srl
         FROM v\$archive_dest_status
         WHERE dest_name IN ('LOG_ARCHIVE_DEST_1', 'LOG_ARCHIVE_DEST_2');

     register: sqloutput
     when:
       - node in groups['oranodes'][1]
     tags: 04_verifgaps

   - name: Show result
     debug:
       msg: |
         ======================================================================
         Log Information for Database: {{ dbname }}
         ======================================================================
         ==> database_mode must be MOUNTED_STANDBY if running DATAGUARD
         ==> database_mode must be OPEN_READ-ONLY if running ACTIVE DATAGUARD
         {{ sqloutput.stdout }}


     when:
       - node in groups['oranodes'][1]
     failed_when: "'no rows selected' in sqloutput.stdout"
     tags: 04_verifgaps
